# Generated by Django 4.0.4 on 2022-05-22 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalGym', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrenador',
            options={'verbose_name': 'Entrenador', 'verbose_name_plural': 'Entrenadores'},
        ),
        migrations.AddField(
            model_name='entrenador',
            name='clase',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='usuario',
            name='claseinscripta',
            field=models.CharField(default='', max_length=30),
        ),
    ]
