# Generated by Django 4.0.4 on 2022-05-25 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinalGym', '0003_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avatar',
            options={'verbose_name': 'Avatar', 'verbose_name_plural': 'Avatares'},
        ),
    ]
